export default {
  BATTERY_STATUS: "BATTERY_STATUS",
  FORCED_OFFLINE: "FORCED_OFFLINE",
  ENERGY_OFFLINE: "ENERGY_OFFLINE",
  NETWORK_STATUS: "NETWORK_STATUS",
  IS_SYNCHRONIZED: "IS_SYNCHRONIZED"
}
