export default {
  ADD_WORDS_REQUEST: "ADD_WORDS_REQUEST",
  ADD_WORDS_SUCCESS: "ADD_WORDS_SUCCESS",
  ADD_WORDS_FAILURE: "ADD_WORDS_FAILURE",

  GET_WORDS_REQUEST: "GET_WORDS_REQUEST",
  GET_WORDS_SUCCESS: "GET_WORDS_REQUEST",
  GET_WORDS_FAILURE: "GET_WORDS_FAILURE"
}
