export default {
  ADD_WORD_REQUEST: "ADD_WORD_REQUEST",
  ADD_WORD_SUCCESS: "ADD_WORD_SUCCESS",
  ADD_WORD_FAILURE: "ADD_WORD_FAILURE",

  DELETE_WORD_REQUEST: "DELETE_WORD_REQUEST",
  DELETE_WORD_SUCCESS: "DELETE_WORD_SUCCESS",
  DELETE_WORD_FAILURE: "DELETE_WORD_FAILURE",

  GET_WORDS_REQUEST: "GET_WORDS_REQUEST",
  GET_WORDS_SUCCESS: "GET_WORDS_SUCCESS",
  GET_WORDS_FAILURE: "GET_WORDS_FAILURE",

  UPDATE_STATS_REQUEST: "UPDATE_STATS_REQUEST",

  OFFLINE_ADD_WORD: "OFFLINE_ADD_WORD",
  OFFLINE_DELETE_WORD: "OFFLINE_DELETE_WORD",
  OFFLINE_GET_WORDS: "OFFLINE_GET_WORDS",
  COPY_LOCAL_STATE: "COPY_LOCAL_STATE",

  SYNC_OFFLINE_STATE_REQUEST: "SYNC_OFFLINE_STATE_REQUEST",
  SYNC_OFFLINE_STATE_SUCCESS: "SYNC_OFFLINE_STATE_SUCCESS",
  SYNC_OFFLINE_STATE_FAILURE: "SYNC_OFFLINE_STATE_FAILURE",

  OFFLINE_ADD_TO_DELETED_LIST: "OFFLINE_ADD_TO_DELETED_LIST",
  OFFLINE_ADD_TO_ADDED_LIST: "OFFLINE_ADD_TO_ADDED_LIST",
  RESET_LISTS: "RESET_LISTS"

}
