export default {
  ADD_WORD_REQUEST: "ADD_WORD_REQUEST",
  ADD_WORD_SUCCESS: "ADD_WORD_SUCCESS",
  ADD_WORD_FAILURE: "ADD_WORD_FAILURE",

  DELETE_WORD_REQUEST: "DELETE_WORD_REQUEST",
  DELETE_WORD_SUCCESS: "DELETE_WORD_SUCCESS",
  DELETE_WORD_FAILURE: "DELETE_WORD_FAILURE",

  GET_WORDS_REQUEST: "GET_WORDS_REQUEST",
  GET_WORDS_SUCCESS: "GET_WORDS_SUCCESS",
  GET_WORDS_FAILURE: "GET_WORDS_FAILURE",

  UPDATE_STATS_REQUEST: "UPDATE_STATS_REQUEST"
}
